# Generated by Django 3.0.7 on 2020-06-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'TodoItem',
                'verbose_name_plural': 'TodoItems',
            },
        ),
    ]
